### ISSUE TITLE
Can't setup databse

### ISSUE THREAD

**Issue by DarthMax** [macksimiljan/aeternitas_dummy#1]
After checking out the repo I deleted the sqlite database files and tried to run `rake db:setup`. This fails with the following error:

Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
-- create_table("aeternitas_pollable_meta_data", {:force=>:cascade})
   -> 0.0559s
-- create_table("aeternitas_sources", {:primary_key=>"fingerprint", :id=>:string, :force=>:cascade})
rake aborted!
ArgumentError: Index name 'sqlite_autoindex_aeternitas_sources_1' on table 'aeternitas_sources' already exists
/home/max/coding/fraunhofer/aeternitas_dummy/db/schema.rb:27:in `block in <top (required)>'
/home/max/coding/fraunhofer/aeternitas_dummy/db/schema.rb:13:in `<top (required)>'
/home/max/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/home/max/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)

**Comment by macksimiljan** [comment]
I removed the index creation in question from  `schema.rb` as `sqlite_autoindex_aeternitas_sources_1` is automatically created by Sqlite.
